### ISSUE TITLE
Email bounceback and flipped first/family names

### ISSUE THREAD

**Issue by bpbond** [bpbond/cosore#152]
From quazhang - find and fix/remove. In addition @stephpenn1 notes some names are mixed up.

**Comment by bpbond** [comment]
This seems like a good opportunity for you to open your first COSORE pull request @stephpenn1 ?

These data are all stored in the various `CONTRIBUTORS.txt` files in `inst/extdata/datasets/`.

**Comment by stephpenn1** [comment]
### Error entries
- Quan Zhang: email bounceback with `quazhang@indiana.edu`
- Peng Liu: email error with `spiritlover@126.com`
- Karis McFarlane: first and last name switched
- Nina Buchmann: first and last name switched
