### ISSUE TITLE
Potential changes for methane/cosore

### ISSUE THREAD

**Issue by bpbond** [bpbond/cosore#179]
* Lat/lon for individual collars

**Comment by avnimalhotra** [comment]
Other fields to consider but nothing critical: 

-elevation for individual collars
-chamber opaque or not, chamber has mixing fan or not, chamber flow rate, date of chamber installation, chamber volume and equilibrium time
-soil conductivity, salinity, porewater chemistry (C:N, DOC, pH), soil type (ameriflux CVs), disturbance type
-switch free text in vegetation-related fields to CVs (Ameriflux BADM vegtype), consider other veg descriptors from Ameriflux (max height, tissue C:N, %cover by vegtype, clipped or not)

**Comment by bpbond** [comment]
Straightforward to add:

- Latitude, longitude, elevation for individual collars

Already in COSORE:

- Chamber opaque or not

Possible though strike me as super detailed:

- Chamber has mixing fan or not, chamber flow rate, date of chamber installation, chamber volume and equilibrium time
- Note we do have chamber ground area and collar insertion depth
- Which of the above would we rank most important?

These aren't currently in the `ancillary` table but easy to add:

- Soil conductivity, salinity, porewater chemistry (C:N, DOC, pH), soil type (ameriflux CVs), disturbance type

Possible, would like to learn more:

-Switch free text in vegetation-related fields to CVs (Ameriflux BADM vegtype)

Could be added to `ancillary`, but too much work to add to `ports`:

* Consider other veg descriptors from Ameriflux (max height, tissue C:N, %cover by vegtype, clipped or not)

Pinging @dschristianson so she sees this thread

**Comment by avnimalhotra** [comment]
re: Ranking- chamber volume, equilibrium time, date of inst, mixing fan or not, chamber flow. 
But, also happy to forego altogether and reconsider later if they pop up in a lot of datasets/usercases.

Let's discuss the ancillary table additions when you have thought about adding space/time to it. 

**Follow up from today on including multiple gases in data:**
If we are making data table flux columns gas specific. the following would have to be replicated for each gas IF timestamps alligned:
CSR_CDRY
CSR_CO2_AMB
CSR_COMMENTS
CSR_CRVFIT
CSR_ERROR
CSR_FLUX
CSR_FLUX_SE
CSR_R2

But if timestamps are different for each gas then pretty much all data table fields would have to replicate depending on gas other than the labels?


**Follow up from today on soil and veg BADM**

Attaching the two template files from Ameriflux website. I would just adapt something like the VEGTYPE field and SOIL_GROUP. And if you want to get fancy, one could include the following from my powell list:

CH_SPP_PERC | Estimated ground area coverage of each VEGTYPE in chamber (0-100%)
CH_SPP_HEIGHT | average plant height within chamber (m)

Lastly, I would add to the discussion on free text vs CV's that if you already have many datasets with free text on species, I would keep that field in. It's hard to use free text across many sites, but it's still very useful to have in case someone wants to go through and reclassify sites (have done this for multiple syntheses; it's not easy but would have been impossible without species list). 


[BADM-Soil-v2017-Template (2).xlsx](https://github.com/bpbond/cosore/files/4372011/BADM-Soil-v2017-Template.2.xlsx)
[BADM-VegCover-v2018-Template (1).xlsx](https://github.com/bpbond/cosore/files/4372012/BADM-VegCover-v2018-Template.1.xlsx)

**Comment by bpbond** [comment]
>Latitude, longitude, elevation for individual collars

What's the case for these? It has to be more than just "would be nice to have". Is there an analysis that would every realistically use these data?

**Comment by avnimalhotra** [comment]
> > Latitude, longitude, elevation for individual collars
> 
> What's the case for these? It has to be more than just "would be nice to have". Is there an analysis that would every realistically use these data?

Lat long of collars relative to a tower footprint, say, would help determine if tower and collar fluxes can be compared. Elevation in wetlands and other systems with microtopography is a great proxy for various flux drivers (e.g., water table depth). 

I am flexible though as I imagine that these will be rarely reported. Not sure how often people record their chamber x,y and z. I always did it for my manual chambers. 

OR instead of adding them to `port` is it better to add them to `ancillary`?

**Comment by bpbond** [comment]
OK. This is a low-impact change, so I'm willing. No, I think `ports` is definitely the place for that kind of data. Thanks!

**Comment by dschristianson** [comment]
AmeriFlux members have requested the chamber location (lat, long, elev) metadata. The relative distances are needed for any kind of spatial analysis.

**Comment by bpbond** [comment]
OK, added optional lon/lat/elevation for collars.
