### ISSUE TITLE
Phase 2 Community Survey - AmeriFlux

### ISSUE THREAD

**Issue by stephpenn1** [bpbond/cosore#198]
Danielle's suggestions:
- **Timestamps:** are people interested in having timestamps matched up to hourly/half-hourly resolutions to link with tower data? if so, are people okay with e.g. a 5min chamber measurement representative of a 30 minute period
- **Ancillary measurements:** (soil moisture, air temp)... dig into this, what exactly? What's most important for analyses?
- **Data provenance:** what exactly? Access to raw data?
- **Fit metrics:** what should be required? R2?

_Split into phases:_ Data advisory Committee (comment on questions) -> group of soil AmeriFlux people (10-20) -> broad community (listserve, 20)

Timeline:
~month from now - draft of questions... send to data advisory committee

**Comment by stephpenn1** [comment]
@bpbond could you give me more examples of data provenance so i can incorporate a new question in? My understanding is that it can be...
 - access to raw data
- transparency on processing (# of measurements dropped, etc.)
-....?

**Comment by bpbond** [comment]
Those two things for sure. I'd expand the second bullet a bit

* Transparency on processing: transformations/calculations applied, observations or fields dropped, and summarizing that takes place

Thanks!
