### ISSUE TITLE
Get rid of flux limits

### ISSUE THREAD

**Issue by bpbond** [bpbond/cosore#206]
Tana Wood and several other folks have raised this. What if it’s a valid but extraordinarily high flux? Or what if someone wants to do a study of flux distributions, including possible measurement errors?

**Comment by avnimalhotra** [comment]
I agree with this as well (as you know). Esp after looking at the large ranges in CH4 flux from Knox et al. 2019 BAMs.

**Comment by bpbond** [comment]
I just took a look and 13 of the 82 current datasets had CO2 fluxes removed, about 0.9% of their observations, because they went outside the bounds. Reprocessing these should be straightforward.

**Comment by bpbond** [comment]
This has the added benefit of simplifying the code.

**Comment by bpbond** [comment]
...straightforward but slow. 😴
