### ISSUE TITLE
Standardize the data

### ISSUE THREAD

**Issue by jinshijian** [bpbond/cosore#54]
Files within 'dataset' file are organized differently (columns number, the order of columns). Will it better to standardize the format? I mean all the output file have the same columns (maybe just some common columns which all files should have) and in the same order. That will be easier for the user to use and follow.

**Comment by bpbond** [comment]
Thanks @jinshijian . The number of columns is going to differ between datasets; there's no way around that, as they measure different ancillary data (T5 versus T10, etc) that we don't want to just toss out. In addition, it's easy in R to combine data frames with different columns (`dplyr::bind_rows()`, `plyr::rbind.fill()`, `data.table::rbindlist()`, etc).

But having a consistent ordering to the most common columns seems like a good idea. For example, `CSR_TIMESTAMP`, `CSR_FLUX`, and `CSR_PORT` are all guaranteed to be present, and could always appear in that order; anything after that could be alphabetical. Would that partly address this?

**Comment by bpbond** [comment]
Another possibility would be separate the current `data` table into two: 
* `data_core` (guaranteed to have constant fields) and 
* `data_other` (variable fields like `CSR_T5`, `CSR_SM10`, etc).

**Comment by bpbond** [comment]
Thoughts @jinshijian ?
